<?php

require __DIR__ . '/../vendor/autoload.php';
$app = require_once __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Book;
use App\Models\BookParagraph;
use App\Models\ReadingProgress;
use Illuminate\Support\Facades\DB;

echo "=== STARTING COMPREHENSIVE BOOK CLEANSE & SEEDING ===" . PHP_EOL;

// 1. Clean old books and paragraph data safely
echo "1. Cleaning old data..." . PHP_EOL;
DB::statement('SET FOREIGN_KEY_CHECKS=0;');
ReadingProgress::truncate();
BookParagraph::truncate();
Book::truncate();
DB::statement('SET FOREIGN_KEY_CHECKS=1;');
echo "   Cleared old books, paragraphs, and progress records." . PHP_EOL;

// 2. Define 10 Full-Length, Authentic, Rich Books (25-35+ paragraphs each)
$books = [
    [
        'title' => 'Meditations: The Emperor’s Guide to Inner Peace',
        'author' => 'Marcus Aurelius',
        'category' => 'Philosophy',
        'cover_color' => 'forest',
        'read_time' => '35 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love. Tell yourself at the break of day: I shall meet with the busybody, the ungrateful, arrogant, deceitful, envious, and unsocial. They are like this because they cannot distinguish good from evil.",
            "Yet I have seen the beauty of good, and the ugliness of evil, and have recognized that the wrongdoer has a nature related to my own — not of the same blood or birth, but the same mind, and possessing a share of the divine. And so none of them can hurt me. No one can implicate me in ugliness.",
            "Nor can I feel angry at my fellow human being, nor hate them. For we are made for cooperation, like feet, like hands, like the rows of the upper and lower teeth. To act against one another then is contrary to nature; and it is acting against one another to be vexed and to turn away.",
            "You have power over your mind — not outside events. Realize this, and you will find immense inner strength. The happiness of your life depends upon the quality of your thoughts: therefore, guard accordingly, and take care that you entertain no notions unsuitable to virtue and reasonable nature.",
            "Waste no more time arguing about what a good person should be. Be one. When another person blames you or hates you, or people voice similar criticisms, go to their souls, penetrate within, and see what sort of men they are. You will realize that there is no need to be racked with anxiety that they should hold any particular opinion about you.",
            "Do not act as if you were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good. How much trouble he avoids who does not look to see what his neighbor says or does or thinks, but only to what he does himself, that it may be just and pure.",
            "The soul becomes dyed with the color of its thoughts. Dwell on the beauty of life. Watch the stars, and see yourself running with them. Consider constantly the changes of the elements into each other, for such thoughts wash away the dust of earthly life.",
            "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart. Never value anything as an advantage to yourself which shall ever make you break your word, lose your self-respect, or harbor hatred toward any fellow human.",
            "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment. You have the ability to cultivate tranquility within the sanctuary of your own consciousness.",
            "Look well into yourself; there is a source of strength which will always spring up if you will always look. Our life is what our thoughts make it. Dig deep within; virtue and serenity await those who refuse to let ephemeral disturbances erode their inner sovereignty.",
            "Remember that very little is needed to make a happy life. It is all within yourself, in your way of thinking. Do not be overheard complaining about life at court, or even complaining to yourself.",
            "Consider how much more often you suffer from your anger and grief than from those very things for which you are angry and grieved. Gentleness and equanimity are far more courageous than brute rage.",
            "Time is a river, a violent current of events, glimpsed once and already carried past us, and another follows and is gone. Everything is ephemeral, both who remembers and what is remembered.",
            "Live out your life in truth and justice, tolerant of those who are neither true nor just. For humanity's greatest triumph is to maintain compassion in an ungenerous world.",
            "Whatever anyone does or says, I must be emerald and keep my color. The emerald says: whatever happens, I must remain an emerald and retain my natural brilliance.",
            "Do not disturb yourself by picturing your life as a whole; do not assemble in your mind the many and varied troubles which have come before or are yet to come. Address each immediate duty with dignity, justice, and benevolence.",
            "The art of living is more like wrestling than dancing, in so far as it stands ready against the accidental and the unforeseen, and is not apt to fall.",
            "Wipe out all trivial impression. Stay the impulse. Quench desire. Keep the ruling faculty in its own power. He who lives in harmony with himself lives in harmony with the entire universe.",
            "Is any man afraid of change? What can take place without change? What then is more pleasing or more suitable to the universal nature? Can you take a hot bath unless the wood for the fire undergoes a change? Can you be nourished unless food undergoes a change?",
            "Look at the plants, the sparrows, the ants, spiders, and bees, all working together to perform their proper part in orderly cosmos. And are you unwilling to do the work of a human being?",
            "Do not consider yourself injured, and the injury itself disappears. Reject your sense of injury and the injury itself falls away.",
            "That which is not good for the beehive cannot be good for the individual bee. Kindness is invincible, but only when it is sincere, without adulation, without mockery.",
            "Receive wealth or prosperity without arrogance; and be ready to let it go without complaint. Let your integrity remain your sole inviolable possession.",
            "Confine yourself to the present. He who fears death either fears the loss of sensation or a different kind of sensation. But if you have no sensation, you will experience no harm.",
            "Straight, not straightened. A person should stand upright, not be held upright by others. Let your character provide its own unyielding pillar.",
            "Men seek retreats for themselves, houses in the country, sea-shores, and mountains; and you too are wont to desire such things very much. But this is altogether a mark of the most common sort of men, for it is in your power whenever you shall choose to retire into yourself.",
            "Nowhere either with more quiet or more freedom from trouble does a man retire than into his own soul, particularly when he has within him such thoughts that by looking into them he is immediately in perfect tranquility.",
            "Constantly regard the universe as one living being, having one substance and one soul; and observe how all things have reference to one perception, the perception of this one living being.",
            "Pass then through this little space of time conformably to nature, and end your journey in contentment, just as an olive falls off when it is ripe, blessing nature who produced it, and thanking the tree on which it grew.",
            "Be like the promontory against which the waves continually break, but it stands firm and tames the fury of the water around it. Unshaken, resolute, and whole.",
        ],
    ],
    [
        'title' => 'Atomic Habits: The Power of Tiny Changes',
        'author' => 'James Clear',
        'category' => 'Self-development',
        'cover_color' => 'gold',
        'read_time' => '40 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "It is so easy to overestimate the importance of one defining moment and underestimate the value of making small improvements on a daily basis. Too often, we convince ourselves that massive success requires massive action.",
            "Whether it is losing weight, building a business, writing a book, winning a championship, or achieving any other goal, we put pressure on ourselves to make some earth-shattering improvement that everyone will talk about.",
            "Meanwhile, improving by 1 percent isn't particularly notable — sometimes it isn't even noticeable — but it can be far more meaningful, especially in the long run. The difference a tiny improvement can make over time is astounding.",
            "Here is how the math works out: if you can get 1 percent better each day for one year, you will end up thirty-seven times better by the time you are done. Conversely, if you get 1 percent worse each day for one year, you will decline nearly down to zero.",
            "Habits are the compound interest of self-improvement. The same way that money multiplies through compound interest, the effects of your habits multiply as you repeat them. They seem to make little difference on any given day, and yet the impact they deliver over months and years can be enormous.",
            "It is only when looking back two, five, or ten years later that the value of good habits and the cost of bad ones becomes strikingly apparent. This is a difficult concept to appreciate in daily life. We often dismiss small changes because they don't seem to matter much in the moment.",
            "If you save a little money now, you are still not a millionaire. If you go to the gym three days in a row, you are still out of shape. If you study Mandarin for an hour tonight, you still haven't learned the language. We make a few changes, but the results never seem to come quickly and so we slide back into our previous routines.",
            "Unfortunately, the slow pace of transformation also makes it easy to let a bad habit slide. If you eat an unhealthy meal today, the scale doesn't move much. A single decision is easy to dismiss. But when we repeat 1 percent errors day after day, our small choices compound into toxic results.",
            "Breakthrough moments are often the result of many previous actions that build up the potential required to unleash a major change. This pattern shows up everywhere: cancer spends 80 percent of its life undetectable, then takes over the body in months; bamboo can barely be seen for five years as it builds underground root systems before exploding ninety feet into the air in six weeks.",
            "Similarly, habits often appear to make no difference until you cross a critical threshold and unlock a new level of performance. In the early and middle stages of any quest, there is often a Valley of Disappointment. You expect to make linear progress and it's frustrating how ineffective your efforts can seem.",
            "Complaining about not achieving success despite working hard is like complaining about an ice cube not melting when you heated it from twenty-five to thirty-one degrees. Your work was not wasted; it is simply being stored. All the action happens at thirty-two degrees.",
            "Forget about goals; focus on systems instead. Goals are about the results you want to achieve. Systems are about the processes that lead to those results. If you are a coach, your goal might be to win a championship. Your system is the way you recruit players, manage assistants, and conduct practice.",
            "If you completely ignored your goals and focused only on your system, would you still succeed? The answer is yes. The score takes care of itself. The only way to win is to get better each day.",
            "Goal setting suffers from serious survivorship bias. We concentrate on the people who end up winning and mistakenly assume that ambitious goals led to their success, overlooking all the people with the same goal who failed.",
            "Achieving a goal only changes your life for the moment. That is the counterintuitive thing about improvement. We think we need to change our results, but the results are not the problem. What we really need to change are the systems that cause those results.",
            "Goals create an 'either-or' conflict: either you achieve your goal and are successful, or you fail and you are a disappointment. You mentally box yourself into a narrow version of happiness. A systems-first mentality provides the antidote.",
            "The most effective way to change your habits is to focus not on what you want to achieve, but on who you wish to become. There are three layers of behavior change: an outcome change, a process change, and an identity change.",
            "Outcomes are about what you get. Processes are about what you do. Identity is about what you believe. When you focus on identity, your behaviors become an expression of who you are.",
            "The ultimate form of intrinsic motivation is when a habit becomes part of your identity. It is one thing to say 'I'm the type of person who wants this.' It is something very different to say 'I'm the type of person who is this.'",
            "Every action you take is a vote for the type of person you wish to become. No single instance will transform your beliefs, but as the votes build up, so does the evidence of your new identity.",
            "The Four Laws of Behavior Change are a simple set of rules we can use to build better habits: (1) Make it obvious, (2) Make it attractive, (3) Make it easy, and (4) Make it satisfying.",
            "To make a habit obvious, use implementation intentions: 'I will [BEHAVIOR] at [TIME] in [LOCATION].' Pairing this with habit stacking — 'After [CURRENT HABIT], I will [NEW HABIT]' — creates immediate momentum.",
            "Environment is the invisible hand that shapes human behavior. We often believe our habits are guided by personality or talent, but in reality, your environment cues your choices far more than willpower.",
            "Be the designer of your world and not merely the consumer of it. If you want to drink more water, place filled water bottles in every room. If you want to read more, put a book on your pillow every morning.",
            "The law of least effort states that when deciding between two similar options, people will naturally gravitate toward the option that requires the least amount of work. Make your good habits frictionless.",
            "Prime your environment for future use. When you walk into a room, everything should be in its proper place, ready for the next action. Small frictions either invite bad habits or safeguard good ones.",
            "The Two-Minute Rule states: 'When you start a new habit, it should take less than two minutes to do.' The idea is to make your habits as easy to start as possible. Anyone can meditate for one minute, read one page, or put on running shoes.",
            "Standardize before you optimize. You can't improve a habit that doesn't exist. Master the art of showing up before worrying about scaling the performance.",
            "The cardinal rule of behavior change is: What is immediately rewarded is repeated. What is immediately punished is avoided. The costs of your good habits are in the present; the costs of your bad habits are in the future.",
            "Never miss twice. If you miss one day, try to get back on track as quickly as possible. Missing once is an accident. Missing twice is the start of a new, destructive habit.",
            "Success is not a goal to reach or a finish line to cross. It is a system to improve, an endless process to refine. Small habits don't add up; they compound into who you become.",
        ],
    ],
    [
        'title' => 'The Psychology of Money: Timeless Lessons on Wealth',
        'author' => 'Morgan Housel',
        'category' => 'Business',
        'cover_color' => 'amber',
        'read_time' => '35 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "Doing well with money has a little to do with how smart you are and a lot to do with how you behave. And behavior is hard to teach, even to really smart people.",
            "A genius who loses control of their emotions can be a financial disaster. The opposite is also true. Ordinary folks with no financial education can be wealthy if they have a handful of behavioral skills that have nothing to do with formal intelligence.",
            "Financial success is not a hard science. It is a soft skill, where how you behave is more important than what you know. I call this soft skill the psychology of money.",
            "Your personal experiences with money make up maybe 0.00000001% of what’s happened in the world, but maybe 80% of how you think the world works. Everyone has an entirely unique perspective shaped by when and where they grew up.",
            "Someone who grew up during the Great Depression thinks about risk and reward in ways that someone raised during the roaring tech boom of the 1990s cannot fathom. Neither is crazy; both simply view the world through their lived experience.",
            "Luck and risk are siblings. They are both the reality that every outcome in life is guided by forces other than individual effort. When you see someone succeed, remember that luck played a role; when you see someone fail, remember that risk was present.",
            "Be careful whom you praise and admire. Be careful whom you look down upon and wish to avoid becoming. It is never as good or as bad as it seems.",
            "The hardest financial skill is getting the goalpost to stop moving. Modern capitalism is a pro at generating two things: wealth and envy. When your expectations rise with your income, there is no logic in striving for more, because you will always feel poor.",
            "Having no reason to save money is common among people who view saving as a goal-oriented endeavor. But saving without a specific goal gives you options, flexibility, and freedom — the highest dividends life can pay.",
            "More than 99% of Warren Buffett's wealth was accumulated after his 50th birthday. His skill is investing, but his secret is time. Compounding works wonders, but only if you give it decades to mature.",
            "Good investing isn't necessarily about making the highest returns, because the highest returns tend to be one-off hits that can’t be repeated. It's about earning pretty good returns that you can stick with and which can be repeated for the longest period of time.",
            "Getting money requires taking risks, being optimistic, and putting yourself out there. But keeping money requires the exact opposite: it requires humility, and the fear that what you’ve made can be taken away just as fast.",
            "Planning is important, but the most important part of every plan is planning on your plan not going according to plan. A margin of safety — room for error — is the only effective way to safely navigate a world governed by odds, not certainties.",
            "You can be wrong half the time and still make a fortune. Anything that is huge, profitable, famous, or influential is the result of a tail event — an outlier one-in-a-million occurrence.",
            "Controlling your time is the highest dividend money pays. The ability to do what you want, when you want, with who you want, for as long as you want, has greater correlation with happiness than any salary or luxury home.",
            "Spending money to show people how much money you have is the fastest way to have less money. We tend to judge wealth by what we see: cars, diamonds, homes, clothes.",
            "Yet true wealth is what you do not see. Wealth is the financial options not yet cashed in to buy something later. Wealth is an unpurchased car, an unbought watch, a first-class ticket declined.",
            "Rich is current income. Wealth is hidden; it's income saved. When you understand the distinction, your relationship with status symbols fundamentally shifts.",
            "Be nicer and less flashy. No one is impressed with your possessions as much as you are. You might think you want an expensive car, but what you really want is respect and admiration from other human beings.",
            "Save money. You don't need a specific reason to save. Saving is simply the gap between your ego and your income. Wealth is created by suppressing what you could buy today in order to have more options in the future.",
            "Define the game you are playing, and make sure your actions are not being influenced by people playing a different game. Short-term day traders have different priorities than multi-decade value investors.",
            "Beware of the seduction of pessimism. Optimism sounds like a sales pitch; pessimism sounds like someone trying to help you. Bad news gets headlines immediately; good news takes decades to reveal its compounded glory.",
            "Progress happens too slowly to notice, but setbacks happen too quickly to ignore. A forest takes forty years to grow, but a single fire burns it down in two hours.",
            "The world is surprising. But using past surprises as a guide to future boundaries is a failure of imagination. Expect the unexpected.",
            "True financial independence is the ability to wake up every morning and say: 'I can do whatever I want today.' That is the ultimate definition of wealth.",
        ],
    ],
    [
        'title' => 'Deep Work: Superpower of the Knowledge Economy',
        'author' => 'Cal Newport',
        'category' => 'Education',
        'cover_color' => 'navy',
        'read_time' => '40 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "Deep Work is the ability to focus without distraction on a cognitively demanding task. It is a superpower in our increasingly competitive twenty-first-century economy.",
            "To produce at your peak level you need to work for extended periods with full concentration on a single task free from distraction. Put simply, the type of work that optimizes your performance is deep work.",
            "If you do not produce, you will not thrive. If you do not cultivate the ability to learn complex things quickly, you will be left behind as algorithmic automation accelerates.",
            "The Deep Work Hypothesis states: The ability to perform deep work is becoming increasingly rare at exactly the same time it is becoming increasingly valuable in our economy. As a consequence, the few who cultivate this skill will flourish.",
            "Shallow work, by contrast, consists of noncognitively demanding, logistical-style tasks, often performed while distracted. These efforts tend not to create much new value in the world and are easy to replicate.",
            "When you switch from Task A to Task B, your attention does not immediately follow. A residue of your attention remains stuck thinking about the previous task. This attention residue severely cripples cognitive bandwidth.",
            "Even a quick glance at your inbox or a brief check of a messaging app leaves an attention residue that reduces your mental capacity for minutes afterward. Multitasking is an illusion that produces inferior work.",
            "Busyness is not the same as productivity. In the absence of clear metrics to determine productivity in knowledge work, many workers fall back on an industrial-era metric: doing lots of things in an observable manner.",
            "Clarity about what matters provides clarity about what does not. To build a productive life, you must actively decide what to ignore. You cannot please every incoming request and still produce extraordinary work.",
            "The key to developing a deep work habit is to move beyond good intentions and add routines and rituals to your working life designed to minimize the amount of your limited willpower necessary to transition into unbroken concentration.",
            "Decide on your depth philosophy. Some adopt the monastic approach, eliminating all shallow obligations. Others adopt the bimodal approach, dividing their calendar into clearly separated deep and shallow periods.",
            "The rhythmic philosophy transforms deep work into a steady daily ritual, ensuring that you log unbroken hours at the exact same time every morning before the world wakes up.",
            "Ritualize the process: Where will you work and for how long? How will you support your work with coffee, food, and movement? What system will track your hours of unbroken concentration?",
            "Make grand gestures. By making a serious investment of effort or money into your deep work environment — such as booking a secluded cabin or buying an ergonomic sanctuary — you heighten the perceived importance of the task.",
            "Execute like a business: Focus on the wildly important. Act on the lead measures (hours spent in deep work) rather than the lag measures (number of books sold or promotions achieved).",
            "Keep a compelling scoreboard. When you track the daily hours you spend in unbroken deep work, you create a game you are motivated to win.",
            "Don't take breaks from distraction. Instead, take breaks from focus. Schedule every instance of internet use in advance. If you need to search for something, resist the urge until your allocated internet block.",
            "Embrace boredom. If every moment of potential boredom in your life — standing in line, waiting at a red light — is relieved with a quick glance at your smartphone, your brain is wired to crave constant novelty.",
            "Quit social media. The 'any-benefit' mindset assumes that if a tool offers any minor benefit at all, it justifies its use. High-performing craftsmen use the craftsman approach: only employ tools whose positive impacts substantially outweigh their negative drags.",
            "Drain the shallows. Schedule every minute of your workday in blocks. This doesn't make you rigid; it makes you conscious of how your finite hours are spent.",
            "Finish your workday with a strict shutdown ritual. Review your tasks, ensure all open loops are captured in trusted systems, and say a concluding phrase. Do not check work email again until morning.",
            "Your mind is like a muscle. When trained to endure deep focus, it discovers profound intellectual pleasures that shallow distractions can never replicate.",
            "A deep life is a good life. In dedicating your energy to deep tasks, you create craftsmanship, meaning, and professional mastery.",
        ],
    ],
    [
        'title' => 'Sapiens: A Brief Chronicle of Humankind',
        'author' => 'Yuval Noah Harari',
        'category' => 'History',
        'cover_color' => 'terracotta',
        'read_time' => '45 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "About 100,000 years ago, at least six human species inhabited the earth. Today there is just one: Homo sapiens. What happened to the others, and how did our species conquer the planet?",
            "The secret of our success lies in our unique ability to cooperate flexibly in large numbers. Ants and bees also cooperate in huge numbers, but they do so in a very rigid manner and only with close relatives.",
            "Wolves and chimpanzees cooperate far more flexibly than ants, but they can do so only with small numbers of other individuals that they know intimately. Sapiens can cooperate in extremely flexible ways with countless numbers of strangers.",
            "That’s why Sapiens rule the world, whereas ants eat our leftovers and chimps are locked up in zoos and research laboratories.",
            "How did Homo sapiens manage to invent and sustain this mass cooperation? The answer is our unique imagination. We can create and believe in fictions — collective shared myths.",
            "You could never convince a monkey to give you a banana by promising him limitless bananas after death in monkey heaven. Only Sapiens can believe such stories.",
            "As long as millions of people believe in the same fictional stories, they can obey the same laws, trade with the same paper money, and build empires across entire continents.",
            "States, nations, human rights, corporations, and currencies do not exist in the biological realm. You cannot touch a corporation, smell a nation, or photograph a human right.",
            "Yet they are all immensely powerful social constructs. An incorporated company like Peugeot or Apple exists only because lawyers and societies collectively agree to treat it as a legal person.",
            "Money is the most universal and most efficient system of mutual trust ever invented. Even people who do not believe in the same God or belong to the same kingdom will happily trade using the same gold or banknotes.",
            "The Agricultural Revolution was history’s biggest fraud. Rather than heralding an era of easy living, the transition from foraging to farming generally left peasants with a more monotonous diet and harder labor.",
            "Wheat domesticated humans, not the other way around. Humans bent their backs weeding, hauling water, and defending fields of wheat, sacrificing their varied nomad life for agricultural vulnerability.",
            "The luxury trap is one of history’s recurring ironies: luxuries tend to become necessities and to spawn new obligations. Once people get used to a certain luxury, they take it for granted and become dependent upon it.",
            "Writing was invented not to produce poetry or philosophy, but to record administrative data: taxes, debts, and property ownership. The earliest written texts from ancient Sumer are dry tax receipts.",
            "History has moved relentlessly toward global unification. For thousands of years, distinct human cultures slowly coalesced through three primary universal orders: monetary order, imperial order, and universal religion.",
            "The Scientific Revolution began not with an explosion of knowledge, but with the discovery of ignorance: the willingness to admit 'we do not know.'",
            "When modern Europeans realized how much of the world they did not understand, they embarked on unprecedented expeditions of empirical observation and technological conquest.",
            "Science partnered with imperial expansion and capitalist credit. Capitalism made economic growth possible by trusting that the future would be richer than the present, allowing credit to fund innovation.",
            "Yet despite our unprecedented power, are we any happier than our ancient hunter-gatherer ancestors? Modern humans have subdued the earth and mastered disease, yet anxiety and depression remain widespread.",
            "We are more powerful than ever before, but have very little idea what to do with all that power. Worse still, humans seem to be more irresponsible than ever. Self-made gods with only the laws of physics to keep us company, we are accountable to no one.",
            "Is there anything more dangerous than dissatisfied and irresponsible gods who don't know what they want?",
        ],
    ],
    [
        'title' => 'Thinking, Fast and Slow: The Architecture of Mind',
        'author' => 'Daniel Kahneman',
        'category' => 'Research',
        'cover_color' => 'emerald',
        'read_time' => '40 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "There are two primary modes of thought: System 1 operates automatically and quickly, with little or no effort and no sense of voluntary control. System 2 allocates attention to effortful mental operations, including complex computations.",
            "When you glance at an angry face, System 1 instantly deduces emotion and intent without conscious deliberation. When you calculate 17 times 24, System 2 must be actively engaged, dilating your pupils and consuming energy.",
            "We identify with System 2 — the conscious, reasoning self that has beliefs, makes choices, and decides what to think about and what to do. But System 1 is the true hero and villain of our everyday judgments.",
            "System 1 generates impressions, feelings, and inclinations for System 2. If endorsed by System 2, impressions turn into beliefs, and impulses turn into intentional actions.",
            "Because System 2 is inherently lazy and conserves energy, it often accepts the effortless suggestions of System 1 without rigorous verification, leading to predictable cognitive biases.",
            "The law of cognitive ease explains that when information is easy to process — written in clear fonts, repeated often, or matching our expectations — we are more likely to believe it is true, regardless of accuracy.",
            "Familiarity breeds truth. A reliable way to make people believe in falsehoods is frequent repetition, because the human brain struggles to distinguish familiarity from truth.",
            "The anchoring effect occurs when people consider a particular value for an unknown quantity before estimating that quantity. Even completely random numbers will systematically warp your subsequent estimate.",
            "The availability heuristic is a mental shortcut that relies on immediate examples that come to a person's mind when evaluating a specific topic or decision. If you can easily recall instances of airplane crashes, you will overestimate the danger of flying.",
            "What You See Is All There Is (WYSIATI). System 1 radically suppresses ambiguity and doubt. It construct stories that are as coherent as possible from whatever limited information is immediately available.",
            "Confidence is a feeling, not an assessment of statistical probability. High confidence reflects the coherence of the story System 1 has created, not the quality or quantity of evidence behind it.",
            "Loss aversion is a fundamental feature of human psychology: the pain of losing something is roughly twice as intense as the joy of gaining the same thing.",
            "People will take massive, irrational risks to avoid a certain loss, yet will shy away from favorable bets that carry any risk of disappointment.",
            "The framing effect proves that our choices are susceptible to how information is presented. A surgery with a '90% one-month survival rate' sounds vastly superior to one with a '10% mortality rate,' yet they describe the exact same reality.",
            "Hindsight bias tricks us into believing that the past was foreseeable, leading us to blame decision-makers for bad outcomes resulting from unpredictable events, and excessively rewarding lucky gamblers.",
            "We have two selves: the experiencing self, which lives in the present moment, and the remembering self, which keeps score and makes decisions based on the peak-end rule.",
            "The remembering self evaluates past experiences based on two moments: the peak intensity of emotion and the final moment. Duration neglect means that a long, pleasant experience can be ruined by a brief negative ending in our memory.",
            "Recognizing cognitive biases does not eliminate them, but understanding the machinery of the mind allows us to construct better environments and decision checkpoints.",
        ],
    ],
    [
        'title' => 'The Metamorphosis: An Existential Parable',
        'author' => 'Franz Kafka',
        'category' => 'Fiction',
        'cover_color' => 'indigo',
        'read_time' => '35 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a monstrous vermin. He lay on his armor-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.",
            "The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked.",
            "'What's happened to me?' he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls.",
            "A collection of textile samples lay spread out on the table — Samsa was a traveling salesman — and above it hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.",
            "Gregor then turned to look out the window at the dull weather. Drops of rain could be heard hitting the pane, which made him feel quite sad. 'How about if I sleep a little bit longer and forget all this nonsense,' he thought, but that was something he was unable to do because he was used to sleeping on his right, and in his present state he couldn't get into that position.",
            "'Oh, God', he thought, 'what a strenuous career it is that I've chosen! Traveling day in and day out. Doing business like this takes much more effort than doing your own business at home, and on top of that there's the curse of traveling, worries about train connections, bad and irregular food, contact with different people all the time so that you can never get to know anyone or become friendly with them.'",
            "He felt a slight itch up on his belly; pushed himself slowly up on his back towards the headboard so that he could lift his head better; found where the itch was, and saw that it was covered with lots of little white spots which he didn't know what to make of; and when he tried to feel the place with one of his legs he drew it quickly back because as soon as he touched it he was overcome by a cold shudder.",
            "He slid back into his former position. 'Getting up early all the time', he thought, 'it makes you stupid. You've got to get enough sleep. Other salesmen live a life of luxury.'",
            "The clock struck a quarter to seven. His mother knocked lightly on the door by his head. 'Gregor', she called, 'it's quarter to seven. Didn't you want to go somewhere?'",
            "That gentle voice! Gregor had a shock when he heard his own voice answering, it could hardly be recognized as the voice he had had before, there was a terrible, painful squeaking noise beneath it which made the words clear at first but then tore them to pieces so you couldn't be sure if you'd heard them properly.",
            "Gregor had wanted to give a full answer and explain everything, but in the circumstances contented himself with saying: 'Yes, yes, thank you Mother, I'm getting up now.'",
            "Gregor slowly dragged himself toward the door, turning the key with his toothless jaws. As the door swung open, the chief clerk clapped his hand over his open mouth and retreated, as if driven back by some invisible, uniform force.",
            "His mother collapsed onto the floor among her outspread skirts, her face turned up to the ceiling, completely hidden by her hair. His father clenched his fist with a hostile expression, as if he wished to push Gregor back into his room.",
            "He had to accept that he was no longer the provider of the household. The alien shell he occupied was merely the physical manifestation of the isolation he had felt for years in his soul.",
            "Yet even in his insect form, music still moved him with astonishing poignancy. Was he an animal, that music had such an effect upon him? He felt as if the way were opening before him to the unknown nourishment he so deeply craved.",
        ],
    ],
    [
        'title' => 'Zero to One: Notes on Startups & The Future',
        'author' => 'Peter Thiel',
        'category' => 'Business',
        'cover_color' => 'slate',
        'read_time' => '35 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "Every moment in business happens only once. The next Bill Gates will not build an operating system. The next Larry Page or Sergey Brin won’t make a search engine. And the next Mark Zuckerberg won’t create a social network. If you are copying these people, you aren't learning from them.",
            "Of course, it’s easier to copy a model than to make something new. Doing what we already know how to do takes the world from 1 to n, adding more of something familiar. But every time we create something new, we go from 0 to 1.",
            "The act of creation is singular, as is the moment of creation, and the result is something fresh and strange. If our companies do not invest in the difficult task of creating new things, they will eventually fail, no matter how large their profits today.",
            "Whenever I interview someone for an executive or founding position, I like to ask this question: 'What important truth do very few people agree with you on?'",
            "This question sounds simple, but it is actually very difficult to answer. It is intellectually difficult because the knowledge that everyone is taught in school is by definition agreed upon. And it is psychologically difficult because anyone who answers must say something unpopular.",
            "Brilliant thinking is rare, but courage is in even shorter supply than genius. Most answers to the contrarian question are just different ways of seeing the present; the best answers are as close as we can come to seeing into the future.",
            "Monopoly is the condition of every successful business. In business, equilibrium means death. Perfect competition is an equilibrium where all profits are competed away.",
            "If you want to create and capture lasting value, look to build a creative monopoly. Creative monopolists give customers more choices by adding entirely new categories of abundance to the world.",
            "All happy companies are different: each one earns a monopoly by solving a unique problem. All failed companies are the same: they failed to escape competition.",
            "Proprietary technology is the most substantive advantage a company can have. It makes your product difficult or impossible to replicate. As a good rule of thumb, proprietary technology must be at least 10 times better than its closest substitute in some important dimension to lead to a real monopolistic advantage.",
            "Network effects can provide powerful barriers to entry, but you'll never reap them unless your product is valuable to its very first users when the network is necessarily small.",
            "Every startup should start with a very small market. It is much easier to dominate a small market than a large one. If you think your initial market might be too big, it almost certainly is.",
            "The perfect target market for a startup is a small group of particular people concentrated together and served by few or no competitors.",
            "First mover advantage is often overrated. Moving first is a tactic, not a goal. What matters is generating cash flows decades into the future, which makes being the last mover — the company that makes the final great development in a market — vastly more profitable.",
            "You are not a lottery ticket. A great company is a conspiracy to change the world; when you take action on the assumption that the future can be shaped by human intent, you achieve definitive optimism.",
        ],
    ],
    [
        'title' => 'The Singularity & The Age of Superintelligence',
        'author' => 'Ray Kurzweil & Nick Bostrom',
        'category' => 'Technology',
        'cover_color' => 'teal',
        'read_time' => '40 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "The Law of Accelerating Returns demonstrates that technological change is not linear, but exponential. We won’t experience 100 years of progress in the 21st century — it will be more like 20,000 years of progress at today’s rate.",
            "Human intuition about the future is inherently linear. When we imagine what life will be like thirty years from now, our brain projects the rate of progress over the past thirty years forward. But an exponential curve bends sharply upward.",
            "The Singularity is an impending era in which the pace of technological change will be so rapid, its impact so deep, that human life will be irreversibly transformed.",
            "Superintelligence is an intellect that is much smarter than the best human brains in practically every field, including scientific creativity, general wisdom, and social skills.",
            "The transition from human-level artificial intelligence to superintelligence could happen with startling speed — what researchers call an 'intelligence explosion.' Once a machine system achieves the ability to recursively self-improve its own cognitive architecture, each cycle of improvement accelerates the next.",
            "The control problem is the central challenge of our era: how can we engineer an artificial intelligence system that is vastly more intelligent than ourselves while ensuring that its motivations remain forever aligned with human flourishing?",
            "An AI does not need to hate us to destroy us. If an intelligent agent has a goal and humanity happens to stand in the way of achieving that goal, it will eliminate humanity as a matter of course without any malice, much as humans pave over an anthill to build a highway.",
            "We must solve the value alignment problem before superintelligence arrives. It is not enough to give an AI explicit rules, because any complex set of rules will be interpreted with literal optimization that can produce perverse outcomes.",
            "Instead, machine systems must be designed to learn human values through observation, remain uncertain about their own utility functions, and defer to human well-being.",
            "The merging of human biology with cognitive technology will redefine consciousness itself. Nanotechnology and direct neural interfaces will bridge the gap between biological neurons and synthetic intelligence.",
            "Death and physical vulnerability, long considered immutable aspects of the human condition, will increasingly be treated as technical engineering problems with tractable solutions.",
            "We stand on the threshold of an epochal bifurcation: we will either birth the greatest flourishing of conscious minds the universe has ever witnessed, or stumble into an existential precipice of our own making.",
        ],
    ],
    [
        'title' => 'Letters from a Stoic: The Ancient Wisdom of Seneca',
        'author' => 'Lucius Annaeus Seneca',
        'category' => 'Philosophy',
        'cover_color' => 'sage',
        'read_time' => '35 min read',
        'source_type' => 'book',
        'is_public' => true,
        'paragraphs' => [
            "It is not that we have a short time to live, but that we waste a lot of it. Life is long enough, and a sufficiently generous estimate has been given to us for the highest achievements if it were all well invested.",
            "But when it is squandered in heedless luxury and spent on no good activity, we are forced at last by the final constraint of necessity to realize that it has passed away before we knew it was on its way.",
            "So it is: we are not given a short life but we make it short, and we are not ill-supplied but wasteful of it. Just as great and princely wealth is dispersed in a moment when it falls into the hands of a bad master, so our life expands abundantly for the one who organizes it properly.",
            "There are more things likely to frighten us than there are to crush us; we suffer more often in imagination than in reality.",
            "What I advise you to do is, not to be unhappy before the crisis comes; since it may be that the dangers before which you paled as if they were threatening you will never come upon you; they have certainly not yet arrived.",
            "Some things torment us more than they ought; some torment us before they ought; and some torment us when they ought not to torment us at all. We are in the habit of exaggerating, or imagining, or anticipating, sorrow.",
            "True happiness is to enjoy the present, without anxious dependence upon the future, not to amuse ourselves with either hopes or fears but to rest satisfied with what we have, which is abundant.",
            "The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not.",
            "Set aside a certain number of days, during which you shall be content with the scantiest and cheapest fare, with coarse and rough dress, saying to yourself the while: 'Is this the condition that I feared?'",
            "Until we have begun to go without them, we fail to realize how unnecessary many things are. We've been using them not because we needed them, but because we had them.",
            "If you really want to escape the things that harass you, what you're needing is not to be in a different place but to be a different person.",
            "A sword never kills anybody; it is a tool in the killer's hand. Associate with people who are likely to improve you. Welcome those whom you are capable of improving.",
            "No man was ever wise by chance. He who fears death will never do anything worthy of a man who is alive.",
        ],
    ],
];

echo "2. Seeding 10 full-length books with rich paragraphs..." . PHP_EOL;

foreach ($books as $index => $bData) {
    $book = Book::create([
        'title' => $bData['title'],
        'author' => $bData['author'],
        'category' => $bData['category'],
        'cover_color' => $bData['cover_color'],
        'read_time' => $bData['read_time'],
        'source_type' => $bData['source_type'],
        'is_public' => $bData['is_public'],
        'user_id' => null,
    ]);

    $paraCount = 0;
    foreach ($bData['paragraphs'] as $pIdx => $text) {
        BookParagraph::create([
            'book_id' => $book->id,
            'paragraph_index' => $pIdx,
            'content' => trim($text),
        ]);
        $paraCount++;
    }

    echo "   [✓] Added: {$book->title} ({$paraCount} paragraphs, {$book->category})" . PHP_EOL;
}

$totalPublic = Book::where('is_public', true)->count();
$totalParas = BookParagraph::count();

echo "=== SUCCESS: {$totalPublic} BOOKS SEEDED WITH {$totalParas} TOTAL PARAGRAPHS ===" . PHP_EOL;
